//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public beneficiare()
        {
            this.livraisons = new HashSet<livraison>();
        }
    
        public int IDbeneficiare { get; set; }
        public string nom { get; set; }
        public string sexe { get; set; }
        public Nullable<System.DateTime> dateDeNaissance { get; set; }
        public string situation { get; set; }
        public string adresse { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<livraison> livraisons { get; set; }
    }
}
