//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public beneficiare()
        {
            this.livraisons = new HashSet<livraison>();
        }
    
        public int IDbeneficiare { get; set; }
        public string nom { get; set; }
        public string sexe { get; set; }
        public Nullable<System.DateTime> dateDeNaissance { get; set; }
        public string situation { get; set; }
        public string adresse { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<livraison> livraisons { get; set; }
    }
}
