//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogiDons : DbContext
    {
        public LogiDons()
            : base("name=LogiDons")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<beneficiare> beneficiares { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<donArticle> donArticles { get; set; }
        public virtual DbSet<don> dons { get; set; }
        public virtual DbSet<livraisonDonArticle> livraisonDonArticles { get; set; }
        public virtual DbSet<livraison> livraisons { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<utilisateur> utilisateurs { get; set; }
    }
}
