//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donArticle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donArticle()
        {
            this.livraisonDonArticles = new HashSet<livraisonDonArticle>();
        }
    
        public int IDarticle { get; set; }
        public int IDdon { get; set; }
        public Nullable<decimal> valeur { get; set; }
        public Nullable<int> quantite { get; set; }
        public string description { get; set; }
        public int IDarticleDon { get; set; }
    
        public virtual article article { get; set; }
        public virtual don don { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<livraisonDonArticle> livraisonDonArticles { get; set; }
    }
}
