//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donArticle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donArticle()
        {
            this.livraisonDonArticles = new HashSet<livraisonDonArticle>();
        }
    
        public int IDarticle { get; set; }
        public int IDdon { get; set; }
        public Nullable<decimal> valeur { get; set; }
        public Nullable<int> quantite { get; set; }
        public string description { get; set; }
        public int IDarticleDon { get; set; }
    
        public virtual article article { get; set; }
        public virtual don don { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<livraisonDonArticle> livraisonDonArticles { get; set; }
    }
}
