//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class livraisonDonArticle
    {
        public int IDlivraison { get; set; }
        public int IDarticleDon { get; set; }
        public Nullable<int> quantite { get; set; }
    
        public virtual donArticle donArticle { get; set; }
        public virtual livraison livraison { get; set; }
    }
}
