//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class livraisonDonArticle
    {
        public int IDlivraison { get; set; }
        public int IDarticleDon { get; set; }
        public Nullable<int> quantite { get; set; }
    
        public virtual donArticle donArticle { get; set; }
        public virtual livraison livraison { get; set; }
    }
}
