//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class livraison
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public livraison()
        {
            this.livraisonDonArticles = new HashSet<livraisonDonArticle>();
        }
    
        public int IDlivraison { get; set; }
        public Nullable<System.DateTime> datelivraison { get; set; }
        public int IDbeneficiaire { get; set; }
    
        public virtual beneficiare beneficiare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<livraisonDonArticle> livraisonDonArticles { get; set; }
    }
}
