//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public utilisateur()
        {
            this.dons = new HashSet<don>();
            this.dons1 = new HashSet<don>();
        }
    
        public int IDutilisateur { get; set; }
        public string type { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string telephonetravail { get; set; }
        public string telephoneMaison { get; set; }
        public string telephoneMobile { get; set; }
        public Nullable<decimal> salaire { get; set; }
        public string adresse { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<don> dons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<don> dons1 { get; set; }
    }
}
